GET http://localhost:8001/api/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzI1NzUxMzU2LCJpYXQiOjE3MjU3NTEwNTYsImp0aSI6IjFmNGFjMzM4NWQ3ODQzY2Q5OGE5MmYwYTJjMjNjNjQ2IiwidXNlcl9pZCI6MX0.a732ktpQnuQJ_LxwvaIGf4FkNRo7dtrIvpml18ndHao
